// TCG API — service-to-service contract for the card catalog.
//
// gRPC is the trusted read/write surface used by companion services
// (scrapers, pricing jobs, importers). Public read access goes through
// GraphQL instead.
//
// Data-model rules the contract reflects:
//   * prices live on a card's variants (per printing) and on sealed
//     products, overwritten in place — there is no price history
//   * set sizes are never stored — card_count is always a live count
//   * cards have a GUID id plus an optional TCGplayer product id; card
//     lookups accept either
//   * games and sets have a GUID id with an immutable catalog key
//     ("pokemon", "sv3pt5"); their lookups accept either

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tcgapi/v1/catalog.proto

package tcgapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // GUID
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`           // immutable routing key, unique (e.g. "pokemon")
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"` // ISO 639 alpha-3 ("eng", "jpn"); immutable
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Game) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Game) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Game) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // GUID
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                     // catalog set id (e.g. "sv3pt5"), unique per game, immutable
	Language      string                 `protobuf:"bytes,15,opt,name=language,proto3" json:"language,omitempty"`          // ISO 639 alpha-3 ("eng", "jpn"); immutable
	GameId        string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // games.id GUID
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CardCount     int32                  `protobuf:"varint,7,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`            // live count, never stored
	ReleaseDate   *string                `protobuf:"bytes,9,opt,name=release_date,json=releaseDate,proto3,oneof" json:"release_date,omitempty"` // YYYY-MM-DD
	CardTotal     *int32                 `protobuf:"varint,14,opt,name=card_total,json=cardTotal,proto3,oneof" json:"card_total,omitempty"`     // official printed set size
	LogoUrl       *string                `protobuf:"bytes,10,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Set) Reset() {
	*x = Set{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Set) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Set) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Set) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Set) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Set) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Set) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *Set) GetReleaseDate() string {
	if x != nil && x.ReleaseDate != nil {
		return *x.ReleaseDate
	}
	return ""
}

func (x *Set) GetCardTotal() int32 {
	if x != nil && x.CardTotal != nil {
		return *x.CardTotal
	}
	return 0
}

func (x *Set) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *Set) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Set) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// One printing a card exists in ("Normal", "Holofoil", "Reverse Holofoil",
// "Cold Foil", "Unlimited", "1st Edition", ...) with its current price.
type CardVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // GUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         *float64               `protobuf:"fixed64,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardVariant) Reset() {
	*x = CardVariant{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardVariant) ProtoMessage() {}

func (x *CardVariant) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardVariant.ProtoReflect.Descriptor instead.
func (*CardVariant) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CardVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardVariant) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type Card struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                              // GUID
	TcgplayerId *int32                 `protobuf:"varint,16,opt,name=tcgplayer_id,json=tcgplayerId,proto3,oneof" json:"tcgplayer_id,omitempty"` // TCGplayer product id; unset when not listed there
	Language    string                 `protobuf:"bytes,15,opt,name=language,proto3" json:"language,omitempty"`                                 // ISO 639 alpha-3 ("eng", "jpn"); immutable
	GameId      string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                        // games.id GUID
	SetId       string                 `protobuf:"bytes,4,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`                           // set GUID
	Name        string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Number      string                 `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	Rarity      *string                `protobuf:"bytes,7,opt,name=rarity,proto3,oneof" json:"rarity,omitempty"`
	ImageSmall  *string                `protobuf:"bytes,8,opt,name=image_small,json=imageSmall,proto3,oneof" json:"image_small,omitempty"`
	ImageLarge  *string                `protobuf:"bytes,9,opt,name=image_large,json=imageLarge,proto3,oneof" json:"image_large,omitempty"`
	// The printings this card exists in, with their current prices
	Variants []*CardVariant `protobuf:"bytes,17,rep,name=variants,proto3" json:"variants,omitempty"`
	// When the card row itself last changed
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetTcgplayerId() int32 {
	if x != nil && x.TcgplayerId != nil {
		return *x.TcgplayerId
	}
	return 0
}

func (x *Card) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Card) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Card) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetRarity() string {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return ""
}

func (x *Card) GetImageSmall() string {
	if x != nil && x.ImageSmall != nil {
		return *x.ImageSmall
	}
	return ""
}

func (x *Card) GetImageLarge() string {
	if x != nil && x.ImageLarge != nil {
		return *x.ImageLarge
	}
	return ""
}

func (x *Card) GetVariants() []*CardVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{4}
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // ^[a-z0-9-]{2,32}$
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Language      *string                `protobuf:"bytes,3,opt,name=language,proto3,oneof" json:"language,omitempty"` // ISO 639 alpha-3; defaults to "eng"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateGameRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateGameRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type ListSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Query         *string                `protobuf:"bytes,2,opt,name=query,proto3,oneof" json:"query,omitempty"` // set-name filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetsRequest) Reset() {
	*x = ListSetsRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetsRequest) ProtoMessage() {}

func (x *ListSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetsRequest.ProtoReflect.Descriptor instead.
func (*ListSetsRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *ListSetsRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *ListSetsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

type ListSetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sets          []*Set                 `protobuf:"bytes,1,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetsResponse) Reset() {
	*x = ListSetsResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetsResponse) ProtoMessage() {}

func (x *ListSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetsResponse.ProtoReflect.Descriptor instead.
func (*ListSetsResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *ListSetsResponse) GetSets() []*Set {
	if x != nil {
		return x.Sets
	}
	return nil
}

type CreateSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`                // GUID or key
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                  // immutable catalog id (e.g. "sv3pt5")
	Language      *string                `protobuf:"bytes,10,opt,name=language,proto3,oneof" json:"language,omitempty"` // ISO 639 alpha-3; defaults to "eng"; immutable
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ReleaseDate   *string                `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3,oneof" json:"release_date,omitempty"` // YYYY-MM-DD
	CardTotal     *int32                 `protobuf:"varint,9,opt,name=card_total,json=cardTotal,proto3,oneof" json:"card_total,omitempty"`      // official printed set size
	LogoUrl       *string                `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetRequest) Reset() {
	*x = CreateSetRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetRequest) ProtoMessage() {}

func (x *CreateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetRequest.ProtoReflect.Descriptor instead.
func (*CreateSetRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSetRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *CreateSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateSetRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *CreateSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSetRequest) GetReleaseDate() string {
	if x != nil && x.ReleaseDate != nil {
		return *x.ReleaseDate
	}
	return ""
}

func (x *CreateSetRequest) GetCardTotal() int32 {
	if x != nil && x.CardTotal != nil {
		return *x.CardTotal
	}
	return 0
}

func (x *CreateSetRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

type CreateSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // GUID
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetResponse) Reset() {
	*x = CreateSetResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetResponse) ProtoMessage() {}

func (x *CreateSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetResponse.ProtoReflect.Descriptor instead.
func (*CreateSetResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UpdateSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"` // GUID or key
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`     // set GUID or key
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ReleaseDate   *string                `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3,oneof" json:"release_date,omitempty"` // YYYY-MM-DD
	CardTotal     *int32                 `protobuf:"varint,9,opt,name=card_total,json=cardTotal,proto3,oneof" json:"card_total,omitempty"`      // official printed set size
	LogoUrl       *string                `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSetRequest) Reset() {
	*x = UpdateSetRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSetRequest) ProtoMessage() {}

func (x *UpdateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSetRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSetRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *UpdateSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSetRequest) GetReleaseDate() string {
	if x != nil && x.ReleaseDate != nil {
		return *x.ReleaseDate
	}
	return ""
}

func (x *UpdateSetRequest) GetCardTotal() int32 {
	if x != nil && x.CardTotal != nil {
		return *x.CardTotal
	}
	return 0
}

func (x *UpdateSetRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

type UpdateSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSetResponse) Reset() {
	*x = UpdateSetResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSetResponse) ProtoMessage() {}

func (x *UpdateSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSetResponse.ProtoReflect.Descriptor instead.
func (*UpdateSetResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{13}
}

type DeleteSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"` // GUID or key
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`     // set GUID or key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSetRequest) Reset() {
	*x = DeleteSetRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetRequest) ProtoMessage() {}

func (x *DeleteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSetRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSetRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *DeleteSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemovedCards  int32                  `protobuf:"varint,1,opt,name=removed_cards,json=removedCards,proto3" json:"removed_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSetResponse) Reset() {
	*x = DeleteSetResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetResponse) ProtoMessage() {}

func (x *DeleteSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSetResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSetResponse) GetRemovedCards() int32 {
	if x != nil {
		return x.RemovedCards
	}
	return 0
}

type ListSetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`                // GUID or key
	SetId         string                 `protobuf:"bytes,2,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"` // set GUID or key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetCardsRequest) Reset() {
	*x = ListSetCardsRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetCardsRequest) ProtoMessage() {}

func (x *ListSetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetCardsRequest.ProtoReflect.Descriptor instead.
func (*ListSetCardsRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *ListSetCardsRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *ListSetCardsRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

type ListSetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetCardsResponse) Reset() {
	*x = ListSetCardsResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetCardsResponse) ProtoMessage() {}

func (x *ListSetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetCardsResponse.ProtoReflect.Descriptor instead.
func (*ListSetCardsResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *ListSetCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type SearchCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"` // card-name fragment, min 2 chars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardsRequest) Reset() {
	*x = SearchCardsRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardsRequest) ProtoMessage() {}

func (x *SearchCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardsRequest.ProtoReflect.Descriptor instead.
func (*SearchCardsRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *SearchCardsRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *SearchCardsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardsResponse) Reset() {
	*x = SearchCardsResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardsResponse) ProtoMessage() {}

func (x *SearchCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardsResponse.ProtoReflect.Descriptor instead.
func (*SearchCardsResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *SearchCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // GUID or TCGplayer id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *GetCardRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *GetCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`                                          // GUID or key
	TcgplayerId   *int32                 `protobuf:"varint,10,opt,name=tcgplayer_id,json=tcgplayerId,proto3,oneof" json:"tcgplayer_id,omitempty"` // TCGplayer product id
	Language      *string                `protobuf:"bytes,9,opt,name=language,proto3,oneof" json:"language,omitempty"`                            // ISO 639 alpha-3; defaults to "eng"; immutable
	SetId         string                 `protobuf:"bytes,3,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`                           // set GUID or key
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Number        *string                `protobuf:"bytes,5,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Rarity        *string                `protobuf:"bytes,6,opt,name=rarity,proto3,oneof" json:"rarity,omitempty"`
	ImageSmall    *string                `protobuf:"bytes,7,opt,name=image_small,json=imageSmall,proto3,oneof" json:"image_small,omitempty"`
	ImageLarge    *string                `protobuf:"bytes,8,opt,name=image_large,json=imageLarge,proto3,oneof" json:"image_large,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCardRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *CreateCardRequest) GetTcgplayerId() int32 {
	if x != nil && x.TcgplayerId != nil {
		return *x.TcgplayerId
	}
	return 0
}

func (x *CreateCardRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *CreateCardRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *CreateCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCardRequest) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *CreateCardRequest) GetRarity() string {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return ""
}

func (x *CreateCardRequest) GetImageSmall() string {
	if x != nil && x.ImageSmall != nil {
		return *x.ImageSmall
	}
	return ""
}

func (x *CreateCardRequest) GetImageLarge() string {
	if x != nil && x.ImageLarge != nil {
		return *x.ImageLarge
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // GUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *CreateCardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`                                         // GUID or key
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                             // card GUID or TCGplayer id
	TcgplayerId   *int32                 `protobuf:"varint,9,opt,name=tcgplayer_id,json=tcgplayerId,proto3,oneof" json:"tcgplayer_id,omitempty"` // TCGplayer product id
	SetId         string                 `protobuf:"bytes,3,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`                          // set GUID or key
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Number        *string                `protobuf:"bytes,5,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Rarity        *string                `protobuf:"bytes,6,opt,name=rarity,proto3,oneof" json:"rarity,omitempty"`
	ImageSmall    *string                `protobuf:"bytes,7,opt,name=image_small,json=imageSmall,proto3,oneof" json:"image_small,omitempty"`
	ImageLarge    *string                `protobuf:"bytes,8,opt,name=image_large,json=imageLarge,proto3,oneof" json:"image_large,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateCardRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *UpdateCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCardRequest) GetTcgplayerId() int32 {
	if x != nil && x.TcgplayerId != nil {
		return *x.TcgplayerId
	}
	return 0
}

func (x *UpdateCardRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *UpdateCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCardRequest) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *UpdateCardRequest) GetRarity() string {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return ""
}

func (x *UpdateCardRequest) GetImageSmall() string {
	if x != nil && x.ImageSmall != nil {
		return *x.ImageSmall
	}
	return ""
}

func (x *UpdateCardRequest) GetImageLarge() string {
	if x != nil && x.ImageLarge != nil {
		return *x.ImageLarge
	}
	return ""
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{25}
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          string                 `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // GUID or TCGplayer id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteCardRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *DeleteCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcgapi_v1_catalog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_tcgapi_v1_catalog_proto_rawDescGZIP(), []int{27}
}

var File_tcgapi_v1_catalog_proto protoreflect.FileDescriptor

const file_tcgapi_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17tcgapi/v1/catalog.proto\x12\ttcgapi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe4\x03\n" +
	"\x03Set\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\blanguage\x18\x0f \x01(\tR\blanguage\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"card_count\x18\a \x01(\x05R\tcardCount\x12&\n" +
	"\frelease_date\x18\t \x01(\tH\x00R\vreleaseDate\x88\x01\x01\x12\"\n" +
	"\n" +
	"card_total\x18\x0e \x01(\x05H\x01R\tcardTotal\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\n" +
	" \x01(\tH\x02R\alogoUrl\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0f\n" +
	"\r_release_dateB\r\n" +
	"\v_card_totalB\v\n" +
	"\t_logo_urlJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\b\x10\tJ\x04\b\v\x10\fR\tseries_idR\x06seriesR\vsymbol_textR\fsymbol_image\"V\n" +
	"\vCardVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x01H\x00R\x05price\x88\x01\x01B\b\n" +
	"\x06_price\"\xbb\x04\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\ftcgplayer_id\x18\x10 \x01(\x05H\x00R\vtcgplayerId\x88\x01\x01\x12\x1a\n" +
	"\blanguage\x18\x0f \x01(\tR\blanguage\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x15\n" +
	"\x06set_id\x18\x04 \x01(\tR\x05setId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x06 \x01(\tR\x06number\x12\x1b\n" +
	"\x06rarity\x18\a \x01(\tH\x01R\x06rarity\x88\x01\x01\x12$\n" +
	"\vimage_small\x18\b \x01(\tH\x02R\n" +
	"imageSmall\x88\x01\x01\x12$\n" +
	"\vimage_large\x18\t \x01(\tH\x03R\n" +
	"imageLarge\x88\x01\x01\x122\n" +
	"\bvariants\x18\x11 \x03(\v2\x16.tcgapi.v1.CardVariantR\bvariants\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0f\n" +
	"\r_tcgplayer_idB\t\n" +
	"\a_rarityB\x0e\n" +
	"\f_image_smallB\x0e\n" +
	"\f_image_largeJ\x04\b\x02\x10\x03J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rR\x03keyR\x05priceR\x10price_updated_at\"\x12\n" +
	"\x10ListGamesRequest\":\n" +
	"\x11ListGamesResponse\x12%\n" +
	"\x05games\x18\x01 \x03(\v2\x0f.tcgapi.v1.GameR\x05games\"i\n" +
	"\x11CreateGameRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\blanguage\x18\x03 \x01(\tH\x00R\blanguage\x88\x01\x01B\v\n" +
	"\t_language\"9\n" +
	"\x12CreateGameResponse\x12#\n" +
	"\x04game\x18\x01 \x01(\v2\x0f.tcgapi.v1.GameR\x04game\"J\n" +
	"\x0fListSetsRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x19\n" +
	"\x05query\x18\x02 \x01(\tH\x00R\x05query\x88\x01\x01B\b\n" +
	"\x06_query\"6\n" +
	"\x10ListSetsResponse\x12\"\n" +
	"\x04sets\x18\x01 \x03(\v2\x0e.tcgapi.v1.SetR\x04sets\"\xc8\x02\n" +
	"\x10CreateSetRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1f\n" +
	"\blanguage\x18\n" +
	" \x01(\tH\x00R\blanguage\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\frelease_date\x18\x06 \x01(\tH\x01R\vreleaseDate\x88\x01\x01\x12\"\n" +
	"\n" +
	"card_total\x18\t \x01(\x05H\x02R\tcardTotal\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\a \x01(\tH\x03R\alogoUrl\x88\x01\x01B\v\n" +
	"\t_languageB\x0f\n" +
	"\r_release_dateB\r\n" +
	"\v_card_totalB\v\n" +
	"\t_logo_urlJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\b\x10\tR\x06seriesR\vsymbol_textR\fsymbol_image\"5\n" +
	"\x11CreateSetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x98\x02\n" +
	"\x10UpdateSetRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\frelease_date\x18\x06 \x01(\tH\x00R\vreleaseDate\x88\x01\x01\x12\"\n" +
	"\n" +
	"card_total\x18\t \x01(\x05H\x01R\tcardTotal\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\a \x01(\tH\x02R\alogoUrl\x88\x01\x01B\x0f\n" +
	"\r_release_dateB\r\n" +
	"\v_card_totalB\v\n" +
	"\t_logo_urlJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\b\x10\tR\x06seriesR\vsymbol_textR\fsymbol_image\"\x13\n" +
	"\x11UpdateSetResponse\"6\n" +
	"\x10DeleteSetRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"8\n" +
	"\x11DeleteSetResponse\x12#\n" +
	"\rremoved_cards\x18\x01 \x01(\x05R\fremovedCards\"@\n" +
	"\x13ListSetCardsRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x15\n" +
	"\x06set_id\x18\x02 \x01(\tR\x05setId\"=\n" +
	"\x14ListSetCardsResponse\x12%\n" +
	"\x05cards\x18\x01 \x03(\v2\x0f.tcgapi.v1.CardR\x05cards\">\n" +
	"\x12SearchCardsRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"<\n" +
	"\x13SearchCardsResponse\x12%\n" +
	"\x05cards\x18\x01 \x03(\v2\x0f.tcgapi.v1.CardR\x05cards\"4\n" +
	"\x0eGetCardRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"6\n" +
	"\x0fGetCardResponse\x12#\n" +
	"\x04card\x18\x01 \x01(\v2\x0f.tcgapi.v1.CardR\x04card\"\x80\x03\n" +
	"\x11CreateCardRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12&\n" +
	"\ftcgplayer_id\x18\n" +
	" \x01(\x05H\x00R\vtcgplayerId\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\t \x01(\tH\x01R\blanguage\x88\x01\x01\x12\x15\n" +
	"\x06set_id\x18\x03 \x01(\tR\x05setId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\x06number\x18\x05 \x01(\tH\x02R\x06number\x88\x01\x01\x12\x1b\n" +
	"\x06rarity\x18\x06 \x01(\tH\x03R\x06rarity\x88\x01\x01\x12$\n" +
	"\vimage_small\x18\a \x01(\tH\x04R\n" +
	"imageSmall\x88\x01\x01\x12$\n" +
	"\vimage_large\x18\b \x01(\tH\x05R\n" +
	"imageLarge\x88\x01\x01B\x0f\n" +
	"\r_tcgplayer_idB\v\n" +
	"\t_languageB\t\n" +
	"\a_numberB\t\n" +
	"\a_rarityB\x0e\n" +
	"\f_image_smallB\x0e\n" +
	"\f_image_largeJ\x04\b\x02\x10\x03R\x03key\"$\n" +
	"\x12CreateCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd7\x02\n" +
	"\x11UpdateCardRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12&\n" +
	"\ftcgplayer_id\x18\t \x01(\x05H\x00R\vtcgplayerId\x88\x01\x01\x12\x15\n" +
	"\x06set_id\x18\x03 \x01(\tR\x05setId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\x06number\x18\x05 \x01(\tH\x01R\x06number\x88\x01\x01\x12\x1b\n" +
	"\x06rarity\x18\x06 \x01(\tH\x02R\x06rarity\x88\x01\x01\x12$\n" +
	"\vimage_small\x18\a \x01(\tH\x03R\n" +
	"imageSmall\x88\x01\x01\x12$\n" +
	"\vimage_large\x18\b \x01(\tH\x04R\n" +
	"imageLarge\x88\x01\x01B\x0f\n" +
	"\r_tcgplayer_idB\t\n" +
	"\a_numberB\t\n" +
	"\a_rarityB\x0e\n" +
	"\f_image_smallB\x0e\n" +
	"\f_image_large\"\x14\n" +
	"\x12UpdateCardResponse\"7\n" +
	"\x11DeleteCardRequest\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteCardResponse2\x82\a\n" +
	"\x0eCatalogService\x12F\n" +
	"\tListGames\x12\x1b.tcgapi.v1.ListGamesRequest\x1a\x1c.tcgapi.v1.ListGamesResponse\x12I\n" +
	"\n" +
	"CreateGame\x12\x1c.tcgapi.v1.CreateGameRequest\x1a\x1d.tcgapi.v1.CreateGameResponse\x12C\n" +
	"\bListSets\x12\x1a.tcgapi.v1.ListSetsRequest\x1a\x1b.tcgapi.v1.ListSetsResponse\x12F\n" +
	"\tCreateSet\x12\x1b.tcgapi.v1.CreateSetRequest\x1a\x1c.tcgapi.v1.CreateSetResponse\x12F\n" +
	"\tUpdateSet\x12\x1b.tcgapi.v1.UpdateSetRequest\x1a\x1c.tcgapi.v1.UpdateSetResponse\x12F\n" +
	"\tDeleteSet\x12\x1b.tcgapi.v1.DeleteSetRequest\x1a\x1c.tcgapi.v1.DeleteSetResponse\x12O\n" +
	"\fListSetCards\x12\x1e.tcgapi.v1.ListSetCardsRequest\x1a\x1f.tcgapi.v1.ListSetCardsResponse\x12L\n" +
	"\vSearchCards\x12\x1d.tcgapi.v1.SearchCardsRequest\x1a\x1e.tcgapi.v1.SearchCardsResponse\x12@\n" +
	"\aGetCard\x12\x19.tcgapi.v1.GetCardRequest\x1a\x1a.tcgapi.v1.GetCardResponse\x12I\n" +
	"\n" +
	"CreateCard\x12\x1c.tcgapi.v1.CreateCardRequest\x1a\x1d.tcgapi.v1.CreateCardResponse\x12I\n" +
	"\n" +
	"UpdateCard\x12\x1c.tcgapi.v1.UpdateCardRequest\x1a\x1d.tcgapi.v1.UpdateCardResponse\x12I\n" +
	"\n" +
	"DeleteCard\x12\x1c.tcgapi.v1.DeleteCardRequest\x1a\x1d.tcgapi.v1.DeleteCardResponseBAZ?github.com/lee5i3/pokemon-invest/internal/pb/tcgapi/v1;tcgapiv1b\x06proto3"

var (
	file_tcgapi_v1_catalog_proto_rawDescOnce sync.Once
	file_tcgapi_v1_catalog_proto_rawDescData []byte
)

func file_tcgapi_v1_catalog_proto_rawDescGZIP() []byte {
	file_tcgapi_v1_catalog_proto_rawDescOnce.Do(func() {
		file_tcgapi_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcgapi_v1_catalog_proto_rawDesc), len(file_tcgapi_v1_catalog_proto_rawDesc)))
	})
	return file_tcgapi_v1_catalog_proto_rawDescData
}

var file_tcgapi_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_tcgapi_v1_catalog_proto_goTypes = []any{
	(*Game)(nil),                  // 0: tcgapi.v1.Game
	(*Set)(nil),                   // 1: tcgapi.v1.Set
	(*CardVariant)(nil),           // 2: tcgapi.v1.CardVariant
	(*Card)(nil),                  // 3: tcgapi.v1.Card
	(*ListGamesRequest)(nil),      // 4: tcgapi.v1.ListGamesRequest
	(*ListGamesResponse)(nil),     // 5: tcgapi.v1.ListGamesResponse
	(*CreateGameRequest)(nil),     // 6: tcgapi.v1.CreateGameRequest
	(*CreateGameResponse)(nil),    // 7: tcgapi.v1.CreateGameResponse
	(*ListSetsRequest)(nil),       // 8: tcgapi.v1.ListSetsRequest
	(*ListSetsResponse)(nil),      // 9: tcgapi.v1.ListSetsResponse
	(*CreateSetRequest)(nil),      // 10: tcgapi.v1.CreateSetRequest
	(*CreateSetResponse)(nil),     // 11: tcgapi.v1.CreateSetResponse
	(*UpdateSetRequest)(nil),      // 12: tcgapi.v1.UpdateSetRequest
	(*UpdateSetResponse)(nil),     // 13: tcgapi.v1.UpdateSetResponse
	(*DeleteSetRequest)(nil),      // 14: tcgapi.v1.DeleteSetRequest
	(*DeleteSetResponse)(nil),     // 15: tcgapi.v1.DeleteSetResponse
	(*ListSetCardsRequest)(nil),   // 16: tcgapi.v1.ListSetCardsRequest
	(*ListSetCardsResponse)(nil),  // 17: tcgapi.v1.ListSetCardsResponse
	(*SearchCardsRequest)(nil),    // 18: tcgapi.v1.SearchCardsRequest
	(*SearchCardsResponse)(nil),   // 19: tcgapi.v1.SearchCardsResponse
	(*GetCardRequest)(nil),        // 20: tcgapi.v1.GetCardRequest
	(*GetCardResponse)(nil),       // 21: tcgapi.v1.GetCardResponse
	(*CreateCardRequest)(nil),     // 22: tcgapi.v1.CreateCardRequest
	(*CreateCardResponse)(nil),    // 23: tcgapi.v1.CreateCardResponse
	(*UpdateCardRequest)(nil),     // 24: tcgapi.v1.UpdateCardRequest
	(*UpdateCardResponse)(nil),    // 25: tcgapi.v1.UpdateCardResponse
	(*DeleteCardRequest)(nil),     // 26: tcgapi.v1.DeleteCardRequest
	(*DeleteCardResponse)(nil),    // 27: tcgapi.v1.DeleteCardResponse
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_tcgapi_v1_catalog_proto_depIdxs = []int32{
	28, // 0: tcgapi.v1.Game.updated_at:type_name -> google.protobuf.Timestamp
	28, // 1: tcgapi.v1.Set.created_at:type_name -> google.protobuf.Timestamp
	28, // 2: tcgapi.v1.Set.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: tcgapi.v1.Card.variants:type_name -> tcgapi.v1.CardVariant
	28, // 4: tcgapi.v1.Card.updated_at:type_name -> google.protobuf.Timestamp
	28, // 5: tcgapi.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: tcgapi.v1.ListGamesResponse.games:type_name -> tcgapi.v1.Game
	0,  // 7: tcgapi.v1.CreateGameResponse.game:type_name -> tcgapi.v1.Game
	1,  // 8: tcgapi.v1.ListSetsResponse.sets:type_name -> tcgapi.v1.Set
	3,  // 9: tcgapi.v1.ListSetCardsResponse.cards:type_name -> tcgapi.v1.Card
	3,  // 10: tcgapi.v1.SearchCardsResponse.cards:type_name -> tcgapi.v1.Card
	3,  // 11: tcgapi.v1.GetCardResponse.card:type_name -> tcgapi.v1.Card
	4,  // 12: tcgapi.v1.CatalogService.ListGames:input_type -> tcgapi.v1.ListGamesRequest
	6,  // 13: tcgapi.v1.CatalogService.CreateGame:input_type -> tcgapi.v1.CreateGameRequest
	8,  // 14: tcgapi.v1.CatalogService.ListSets:input_type -> tcgapi.v1.ListSetsRequest
	10, // 15: tcgapi.v1.CatalogService.CreateSet:input_type -> tcgapi.v1.CreateSetRequest
	12, // 16: tcgapi.v1.CatalogService.UpdateSet:input_type -> tcgapi.v1.UpdateSetRequest
	14, // 17: tcgapi.v1.CatalogService.DeleteSet:input_type -> tcgapi.v1.DeleteSetRequest
	16, // 18: tcgapi.v1.CatalogService.ListSetCards:input_type -> tcgapi.v1.ListSetCardsRequest
	18, // 19: tcgapi.v1.CatalogService.SearchCards:input_type -> tcgapi.v1.SearchCardsRequest
	20, // 20: tcgapi.v1.CatalogService.GetCard:input_type -> tcgapi.v1.GetCardRequest
	22, // 21: tcgapi.v1.CatalogService.CreateCard:input_type -> tcgapi.v1.CreateCardRequest
	24, // 22: tcgapi.v1.CatalogService.UpdateCard:input_type -> tcgapi.v1.UpdateCardRequest
	26, // 23: tcgapi.v1.CatalogService.DeleteCard:input_type -> tcgapi.v1.DeleteCardRequest
	5,  // 24: tcgapi.v1.CatalogService.ListGames:output_type -> tcgapi.v1.ListGamesResponse
	7,  // 25: tcgapi.v1.CatalogService.CreateGame:output_type -> tcgapi.v1.CreateGameResponse
	9,  // 26: tcgapi.v1.CatalogService.ListSets:output_type -> tcgapi.v1.ListSetsResponse
	11, // 27: tcgapi.v1.CatalogService.CreateSet:output_type -> tcgapi.v1.CreateSetResponse
	13, // 28: tcgapi.v1.CatalogService.UpdateSet:output_type -> tcgapi.v1.UpdateSetResponse
	15, // 29: tcgapi.v1.CatalogService.DeleteSet:output_type -> tcgapi.v1.DeleteSetResponse
	17, // 30: tcgapi.v1.CatalogService.ListSetCards:output_type -> tcgapi.v1.ListSetCardsResponse
	19, // 31: tcgapi.v1.CatalogService.SearchCards:output_type -> tcgapi.v1.SearchCardsResponse
	21, // 32: tcgapi.v1.CatalogService.GetCard:output_type -> tcgapi.v1.GetCardResponse
	23, // 33: tcgapi.v1.CatalogService.CreateCard:output_type -> tcgapi.v1.CreateCardResponse
	25, // 34: tcgapi.v1.CatalogService.UpdateCard:output_type -> tcgapi.v1.UpdateCardResponse
	27, // 35: tcgapi.v1.CatalogService.DeleteCard:output_type -> tcgapi.v1.DeleteCardResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tcgapi_v1_catalog_proto_init() }
func file_tcgapi_v1_catalog_proto_init() {
	if File_tcgapi_v1_catalog_proto != nil {
		return
	}
	file_tcgapi_v1_catalog_proto_msgTypes[1].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[2].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[3].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[6].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[8].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[10].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[12].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[22].OneofWrappers = []any{}
	file_tcgapi_v1_catalog_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcgapi_v1_catalog_proto_rawDesc), len(file_tcgapi_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcgapi_v1_catalog_proto_goTypes,
		DependencyIndexes: file_tcgapi_v1_catalog_proto_depIdxs,
		MessageInfos:      file_tcgapi_v1_catalog_proto_msgTypes,
	}.Build()
	File_tcgapi_v1_catalog_proto = out.File
	file_tcgapi_v1_catalog_proto_goTypes = nil
	file_tcgapi_v1_catalog_proto_depIdxs = nil
}
